### ISSUE TITLE
Support for SBT 0.12

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt-start-script#20]
SBT is already in release candidate status and I (and many people) are already using it; it's especially useful in combination with Scala 2.10. Moreover, releases would already be cross-compatible with all the 0.12.x series, including RCs. Hence there is no technical reason to wait for SBT 0.12.0 before upgrading this plugin.

Currently I get this error trying to use this plugin:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.startscript#xsbt-start-script-plugin;0.5.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.typesafe.startscript:xsbt-start-script-plugin:0.5.2 (sbtVersion=0.12, scalaVersion=2.9.2)
[warn] 
```

and in the [repo](http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.startscript/xsbt-start-script-plugin/), I find no release for SBT 0.12.

**Comment by Blaisorblade** [comment]
Update: SBT 0.12 has been released, and I see yet no release of this plugin available.

**Comment by dkristian** [comment]
+1; this is the main plugin that is stopping me from moving to 0.12.

I've tried building it to publish locally, but I'm having some problems there too, the latest of which is:

```
[error] /Users/kristian/dev/xsbt-start-script-plugin/project/Build.scala:3: not found: object Keys
[error] import Keys._
[error]        ^
[error] one error found
[error] (compile:compile) Compilation failed
```

I'm sure this (along with the previous errors I've encountered) has something to do with my almost non-existent experience of developing sbt plugins.

If the plugin can't be published in the public repo for whatever reason soon, is it possible to at least post some instructions for publishing it locally from scratch?

**Comment by havocp** [comment]
Hi guys, I am just tied up with some more urgent stuff for now. I can hopefully do this in the coming weeks. I doubt there's any major difficulty here other than the time to ramp up on what's changed in 0.12 and tweak the source accordingly. I don't know any instructions to post in the meantime because the whole task here is to figure out how to do it.

If anyone is able to do the 0.12 port before I do, it would be very welcome.

**Comment by havocp** [comment]
On master I made things build with 0.12.0. I haven't tested/published yet.

**Comment by havocp** [comment]
I published 0.5.3 for 0.12.0 (and not for 0.11.x, but there's nothing exciting people are missing out on, other than 0.12 support)

Please let me know if it doesn't work for you.

**Comment by dkristian** [comment]
That works fine for me. Thanks!

**Comment by Blaisorblade** [comment]
It works fine for me too, thanks!
